---
ID: "bfcf1cde-6f53-48ca-9cc1-98460a46c5db"
Parent: "5acc23b4-b151-5e0b-94e2-9258cd8468bb"
Template: "b2c29dca-131d-555c-a9bc-3752c5d67381"
Path: "/sitecore/content/HeadlessTenant/sitecore-jss-app/Components/Header/Products Header"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230522T085920Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{AF32C98B-C828-42AF-A649-74C1DE3303FB}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f81e0997-21e9-45f1-b3df-c8d7ea9436e6"
    - ID: "903fe9ad-ffe0-50fc-afea-bcbb69aa8c86"
      Hint: headerimg
      Value: |
        <image mediaid="{26C41FCC-963D-4CF5-BE8A-12AC1957B0D5}" />
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230522T091016Z
